### DISCUSSION TITLE
Layout of how the plugin's YAML configuration file could look like.

### DISCUSSION THREAD

**Discussion by Luiz-Micci** [thoughtworks/templify#18] [General]
It is already established that we will use a YAML file as the plugin's configuration file.

We chose YAML because it is commonly used for pipeline automation...

Here's a proposed format:
```yaml
mappings:
  - file: pom.xml
     placeholders:
       - query: /project/groupId
         name: Cookiecutter.param.groupId
  
  - file: ./config/file.properties
    placeholders:
        - query: parametro1
          name: valor1
```
From this format, we need to discuss how this file and its functionality will evolve.
