### DISCUSSION TITLE
Default PlainTextHandler in case of general unstructured files

### DISCUSSION THREAD

**Discussion by Shankytw** [thoughtworks/templify#36] [Ideas]
First of all this plugin is Awesome. 

I am trying this plugin locally with a project (Java, Gradle, MakeFile, Yml) , Most of the case are getting covered by plugin but it doesn't support files like ( build.gradle, Makefile, .sh , readme.md), So I decided to extend it a bit.

I have added two use cases - 
1. I have created a PlainTextHandler and defaulted all unsupported extensions/types mappings to this handler to simply replace within file.
2. We also use Jinja template conditions and trying a way to use if and else conditions within file . We are using comment format to achieve it without affecting actual codebase. Currently using it like this -  query starting with //backstage-template-condition-start to start if condition and //backstage-template-consition-end to end if condition...

Please share your thoughts if this seems a good idea, it would certainly increase adoption since it will cover most of the cases (obviously not very clean way for now) ...

**Comment by Shankytw** [comment]
Also allowing placeholder override per mapping can be another help, Not trying to do wholesale changes in existing code, just trying if some small tweaks can provide required output...

Also I feel getting handlers based on file extension is a bit coupled behaviour, ie. As a user I may want to just use PlainTextHandler for any type of file for placeholder purpose only, I suggest to give type field priority over extension and user should able to pass type as txt even if file is .java file.

Example config that I am using currently to achieve above - 

```
settings: #optional
  placeholder:
    prefix: "{{"
    suffix: "}}"
mappings:
  - file: pom.xml
    placeholders:
      - query: /project/groupId #xpath
        name: values.groupId
      - query: /project/artifactId
        name: values.artifactId
  - file: src/main/java/com/thoughtworks/CryptoConverter.java
    type: txt
    settings:
      placeholder:
        prefix: "{%"
        suffix: "%}"
    placeholders:
      - query: //backstage-template-condition-test-start
        name: " if values.algo is defined and 'AES' in values.algo "
      - query: //backstage-template-condition-test-end
        name: " endif "
  - type: java
    base_dir: src/main/java
    placeholders:
      - query: com.thoughtworks
        name: values.package
  - type: java
    base_dir: src/test/java
    placeholders:
      - query: com.thoughtworks
        name: values.package
  - file: build.gradle
    placeholders:
      - query: JavaVersion.VERSION_20
        name: values.java_version
  - file: build.gradle
    settings:
      placeholder:
        prefix: "{%"
        suffix: "%}"
    placeholders:
      - query: //backstage-template-condition-keycloak-condition-start
        name: "% if values.security is defined and 'Keycloak' in values.security %"
      - query: //backstage-template-condition-keycloak-condition-end
        name: "% endif %"
  - file: Makefile
    settings:
      placeholder:
        prefix: "{%"
        suffix: "%}"
    placeholders:
      - query: //backstage-template-condition-infra-elk-condition-start
        name: " if values.infra is defined and 'elk' in values.infra "
      - query: //backstage-template-condition-infra-elk-condition-end
        name: " endif "
```
