### ISSUE TITLE
[Feature]: From a template.yml config I need to handle the XML placeholders

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#22]
### Problem Statement

From a yaml file like this:
```yaml
mappings:
  - file: pom.xml
    placeholders:
      - query: /project/groupId
        name: Cookiecutter.param.groupId
      - query: /project/artifactId
        name: ${Cookiecutter.test.replace.map.artifactId}
      - query: /project/dependencies/dependency/scope[text()='test']
 ```
 
 I need the `Cookiecutter-Templater-for-Backstage` do the placeholder replacement

### Ideas or possible solutions

Make the `CookieCutterMojo` calls the `ConfigFile`, `PluginConfig` and FileHandler to process and handle the tempalte.yml config
