### ISSUE TITLE
[Feature]: Support replace for Java files

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#28]
### Problem Statement

For Java projects we need to make a replacement on the `packages` and to do so we will need to rename the folder of those `packages`.

Example:

`MyClass.java` has the following `package`:

```java
package com.example;
```
This class will be at the path:

```shell 
src/main/java/com/example
```

The user will need to insert at the config file the new name for it like:
```yaml
type: java_package
base_dir: src/main/java
   placeholders: 
        - query: com.example
           name:  com.{{Cookiecutter.newName}}.example 
```
