### ISSUE TITLE
[Bug]: template.yaml not found.

### ISSUE THREAD

**Issue by BeppeTW** [thoughtworks/templify#29]
### Cookiecutter Configuration

```yaml
mappings:
  - file: pom.xml
    placeholders:
      - query: /project/groupId
        name: Cookiecutter.param.groupId
      - query: /project/artifactId
        name: Cookiecutter.test.replace.map.artifactId
```

### Cookiecutter version

0.0.4

### Steps to Reproduce

Steps to reproduce:

**first scenario** 
1. Create a file template.yaml
2. Run the plugin.

**second scenario**
1. Don't create any template.yml file.
2. Run the plugin.

### Expected Result

An friendly warning about the missing configuration.

### Actual Result

<img width="1415" alt="image" src="https://github.com/twlabs/Cookiecutter-Templater-for-Backstage/assets/129297150/a43cf4bb-52a1-4990-885e-d4f8ff288976">

Internal stack tracer error message exposed.
