### ISSUE TITLE
[Bug]: Internal error near index 1

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#32]
### Cookiecutter Configuration

config file:
```yaml
mappings:
  - file: pom.xml
    placeholders:
      - query: /project/groupId
        name: cookiecutter.groupId
      - query: /project/artifactId
        name: cookiecutter.artifactId
  - type: java
    base_dir: src/main/java
    placeholders:
      - query: br.com.client.sfc.datalake.sfcdatatransferdatalake
        name: cookiecutter.package
```

Project Structure:
![image](https://github.com/twlabs/Cookiecutter-Templater-for-Backstage/assets/129320680/1ac67366-6159-4d84-9fdd-ac029d9b4014)

### Cookiecutter version

0.1.1

### Actual Result

Output from plugin:
![image](https://github.com/twlabs/Cookiecutter-Templater-for-Backstage/assets/129320680/5e73c24a-b496-4dda-860d-511279e63caa)

When run with debug mode:
![image](https://github.com/twlabs/Cookiecutter-Templater-for-Backstage/assets/129320680/f6b02b5f-52c2-4896-a1fb-d4e721476762)
