### ISSUE TITLE
[Feature]: Enable configurable prefix and suffix for placeholders in the plugin's YAML

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#35]
### Problem Statement

Today the placeholder use curly braces in a static way.
Since the new version of Backstage are using dollar sign with curly braces. It is necessary to update the plugin and make it generic to mitigate possibles future changes

### Ideas or possible solutions

Example of a possible  yaml config:

```yaml
config:
  - placeholders:
     prefix: ${{
     sufix: }}
mappings:
  - file: pom.xml
    placeholders:
      - query: /project/groupId
        name: Cookiecutter.param.groupId
      - query: /project/artifactId
        name: Cookiecutter.test.replace.map.artifactId
      - query: /project/dependencies/dependency/scope[text()='test']
        name: Cookiecutter.replace.map.scopes
```
