### ISSUE TITLE
Make `apiVersion` optional in `maven-templify.yml` handlers

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#49]
### What happened
In each handler must include an explicit `apiVersion: v1` entry, for instance:

```yaml
steps:
  - kind: PlainTextHandler
    apiVersion: v1
    spec:
      - files:
          - src/main/java/com/example/demo_with_spring/hello/HelloController.java
          - src/test/java/com/example/demo_with_spring/hello/HelloControllerTest.java
```

If you omit `apiVersion`, the plugin currently fails with a validation error. This forces everyone to repeat `apiVersion: v1`

### What could be expected
The plugin could assume a sensible default (e.g. v1) when apiVersion is not provided, so that:

* Simple configs don’t require boilerplate

* Users upgrading between versions can rely on the plugin’s built-in defaults

### How to reproduce
1. Create a maven-templify.yml without any apiVersion entries.

2. Run mvn com.thoughtworks.templify:templify:create.

3. Observe a failure about missing/invalid apiVersion.

### Proposed solution
Treat apiVersion as optional, defaulting to the current stable version (v1).

Update the schema or config loader so that:

```yaml
- kind: XmlHandler
  spec:
    # no apiVersion line necessary
    - files: …
```
