### ISSUE TITLE
Create a placeholders for directories

### ISSUE THREAD

**Issue by Luiz-Micci** [thoughtworks/templify#50]
### Problem Statement

Templify does not provide a dedicated DirectoryHandler for directory-level placeholder substitutions, forcing everything through file handlers instead

Existing handlers only transform file contents or individual filenames, not whole directory paths

Templify’s current schema doesn’t expose any directory-level specs, blocking advanced use cases like nested directory migrations. 

### Ideas or possible solutions

Introduce a new handler type—DirectoryHandler—with semantics like:

```yaml
- kind: DirectoryHandler
  apiVersion: v1
  spec:
    - query: com/example/demo_with_spring
      replace: "{{ cookiecutter.template_demo_package_path }}"
    baseDir: src/main/java
```
Behavior: move/rename matching directories by applying the placeholder, before file-level handlers run
